#### Ignite PoC project
server:
  port: 9009

ignite:
  useLocal: true
  clientMode: false
  remote:
    host: 10.190.0.25:10800
  login:
    user: ignite
    password: ignite

  actualHost:
    master: 127.0.0.1:47500..47502

  node:
    durable: true

